name: cepfrontend
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_tts: ^4.2.2
  http: ^1.6.0
  web_socket_channel: ^3.0.1
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Taviraj
      fonts:
        - asset: assets/fonts/Taviraj-Regular.ttf
        - asset: assets/fonts/Taviraj-Medium.ttf
          weight: 500
        - asset: assets/fonts/Taviraj-Bold.ttf
          weight: 700
